In [2]:
## Will replace all the manual function in the previous pipeline with nn module
import torch
import torch.nn as nn

# Create a model class
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1) # Give the input and output 
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features) # z = wx + b
        out = self.sigmoid(out)
        return out     
    

In [3]:
## Making a random dataset
features = torch.rand(10,5)

# Creating Model
model = Model(features.shape[1]) # number of features

# call model for forward pass
model(features) # the forward method triggers automatically as soon as we call the model


tensor([[0.3966],
        [0.4373],
        [0.4683],
        [0.3746],
        [0.4039],
        [0.4517],
        [0.4408],
        [0.4301],
        [0.4349],
        [0.4522]], grad_fn=<SigmoidBackward0>)

In [4]:
# showing weights
model.linear.weight

Parameter containing:
tensor([[ 0.0615, -0.2752, -0.0887,  0.4088, -0.1773]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([-0.3496], requires_grad=True)

In [6]:
# To visualize the whole network
# ! pip install torchinfo
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [18]:
## Making another complex network
# 5 inputs -> hidden layer(3 neuron) -> output layer(1)

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):
        # We define the neural network architecture here
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1) # Since output from previous layer was 3. So input here is 3 and output is 1
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        
        output = self.linear1(features)
        output = self.relu(output)
        output = self.linear2(output)
        output = self.sigmoid(output)

        return output
        # In order to avoid passing the features from every layer in the forward process, we can use Sequential containers

In [19]:
# create dataset
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.6413],
        [0.6298],
        [0.6207],
        [0.6368],
        [0.6315],
        [0.6314],
        [0.6530],
        [0.6241],
        [0.6558],
        [0.6175]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear1.weight
# model.linear2.weight

Parameter containing:
tensor([[ 0.2914, -0.1678,  0.0703,  0.0012,  0.0192],
        [ 0.1703, -0.1278,  0.0600, -0.3280, -0.0812],
        [ 0.2959,  0.2195, -0.1318,  0.1763, -0.1337]], requires_grad=True)

In [21]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3983, -0.0879, -0.1384]], requires_grad=True)

In [11]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [12]:
# In order to avoid passing the features from every layer in the forward pass, we can use Sequential containers

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):
        # We define the neural network architecture here using Sequential container 
        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
        )

    def forward(self,features):

        output = self.network(features)

        return output


In [13]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.4581],
        [0.4528],
        [0.4579],
        [0.4554],
        [0.4554],
        [0.4596],
        [0.4658],
        [0.4534],
        [0.4604],
        [0.4683]], grad_fn=<SigmoidBackward0>)

## Using Built in loss function and optimizer

In [24]:
loss_function  = nn.BCELoss()
type(loss_function)

torch.nn.modules.loss.BCELoss

In [26]:
# loss = loss_function(y_pred,y_target) - we can directly call and pass predicted and target values

## Incase of shape mismatch between y_pred and y_target, we can use .view function to reshape
# loss = loss_function(y_pred,y_target.view(-1,1)) - view is more efficient then .reshape

In [27]:
## Using built-in optimizer
learning_rate = 0.01
#define optimize (after creating model)
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# No need to update parameters manually
optimizer.step()

# clear gradients
optimizer.zero_grad()


In [ ]:
print()