In [1]:
## Will replace all the manual function in the previous pipeline with nn module
import torch
import torch.nn as nn

# Create a model class
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1) # Give the input and output 
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features) # z = wx + b
        out = self.sigmoid(out)
        return out     
    

In [3]:
## Making a random dataset
features = torch.rand(10,5)

# Creating Model
model = Model(features.shape[1]) # 

# call model for forward pass
model(features) # the forward method triggers automatically as soon as we call the model


tensor([[0.6888],
        [0.7223],
        [0.6626],
        [0.6344],
        [0.6753],
        [0.6943],
        [0.7569],
        [0.6832],
        [0.7054],
        [0.6476]], grad_fn=<SigmoidBackward0>)

In [4]:
# showing weights
model.linear.weight

Parameter containing:
tensor([[ 0.0366,  0.3030,  0.1759,  0.4400, -0.2853]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.4014], requires_grad=True)

In [8]:
# To visualize the whole network
# ! pip install torchinfo
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
## Making another complex network
# 5 inputs -> hidden layer(3 neuron) -> output layer(1)

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):
        # We define the neural network architecture here
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        
        output = self.linear1(features)
        output = self.relu(output)
        output = self.linear2(output)
        output = self.sigmoid(output)

        return output
        # In order to avoid passing the features from every layer in the forward process, we can use Sequential containers

In [15]:
# create dataset
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.3933],
        [0.3900],
        [0.3925],
        [0.3942],
        [0.3944],
        [0.3944],
        [0.3950],
        [0.3944],
        [0.3929],
        [0.3926]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear1.weight

Parameter containing:
tensor([[-0.0526,  0.0558,  0.3919,  0.1086, -0.3213],
        [-0.3782,  0.4224,  0.2755, -0.2417, -0.3675],
        [-0.1353,  0.2540,  0.4445, -0.2511, -0.1490]], requires_grad=True)

In [17]:
model.linear2.weight

Parameter containing:
tensor([[-0.0908, -0.0517,  0.4896]], requires_grad=True)

In [18]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [22]:
# In order to avoid passing the features from every layer in the forward pass, we can use Sequential containers

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):
        # We define the neural network architecture here using Sequential container 
        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
        )

    def forward(self,features):

        output = self.network(features)

        return output


In [23]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.4470],
        [0.4294],
        [0.4042],
        [0.4830],
        [0.4697],
        [0.5167],
        [0.4933],
        [0.4192],
        [0.4639],
        [0.4617]], grad_fn=<SigmoidBackward0>)