## Tensors : A tensor is a number, vector ,matrix or any n-dimentional array.

In [1]:
import torch

In [4]:
t1 = torch.tensor(4.) # 4. is a shorhand for 4.0. Used to create floating point numbers
print(t1)
print(t1.dtype)

tensor(4.)
torch.float32


In [5]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matrix
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])

t3




tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

### To know the dimension of the tensor we can use .shape property of a tensor

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

## Tensor operations and gradients

In [22]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [23]:
# Arithmetic operations
y = w * x + b
y
# We can compute the derivative of y w.r.t. the Tensors with requires_grad set as True i.e. w and b
# To come up with the derivative, we can call the backward method on y
 

tensor(17., grad_fn=<AddBackward0>)

In [24]:
y.backward()
# the derivatives of y w.r.t. the input tensors are stored in the .grad property of the respective tensors.

In [25]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


### Questions
1. Torch vs tensor - Torch is the library that we import and tensor is the data sturucture .

## Linear Regression

In [26]:
## Problem statement : To predict crop yeilds for apples and oranges by looking at the average temperature, rainfall and humidity in a region.

#yield_apple = w11 * temp + w12 * rainfall + w13 * humidity + b1(an additional term called bias which is added to the result)
#yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2

'''
The learning part of the model is to figure out the values of the weights w11, w12, w13, w21, w22, w23 and b1, b2 by looking at the training data to make accurate predictions
for the new data. This is done by adjusting the weights slightly many times to make better predictions, using an optimization technique called gradient descent.
'''


'\nThe learning part of the model is to figure out the values of the weights w11, w12, w13, w21, w22, w23 and b1, b2 by looking at the training data to make accurate predictions\nfor the new data. This is done by adjusting the weights slightly many times to make better predictions, using an optimization technique called gradient descent.\n'

In [27]:
import numpy as np
import torch

### Training Data
#### The data is presented using 2 metrices : inputs and targets 

In [28]:
# Inputs (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [29]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32') 